language: android
jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-25
    # - sys-img-armeabi-v7a-android-23

branches:
  except:
  - /^(?i:feature)-.*$/
  - /^(?i:release)-.*$/

notifications:
  slack: openbase-org:vGz7LO4CvGoGMneYkEm3ON7E
  on_failure: change
  on_success: change	

# disabled because this is a gradle project 
# install:
#  - mvn --settings .travis/settings.xml clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -U -V -q

# before_install:
#  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
#  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.bcomfy
        branch: master
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.bcomfy
        tags: true
